apiVersion: apps/v1
kind: Deployment
metadata:
  name: abominable-deployment
  annotations:
    abominable-static: "initial"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abominable-app
  template:
    metadata:
      labels:
        app: abominable-app
    spec:
      serviceAccountName: abominable-sa
      containers:
      - name: abominable-container
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "Patching Deployment metadata annotation...";
            kubectl patch deployment abominable-deployment \
              --type='merge' \
              -p "{\"metadata\": {\"annotations\": {\"abominable-time\": \"$(date +%s)\"}}}";
            sleep 5;
          done
