apiVersion: apps/v1
kind: Deployment
metadata:
  name: abominable-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abominable-app
  template:
    metadata:
      labels:
        app: abominable-app
    spec:
      containers:
      - name: abominable-container
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "Patching self with random annotation...";
            kubectl patch deployment abominable-deployment \
              -p "{\"spec\": {\"template\": {\"metadata\": {\"annotations\": {\"abominable-time\": \"$(date +%s)\"}}}}}";
            sleep 60;
          done
        env:
        - name: KUBERNETES_SERVICE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
      restartPolicy: Always
