apiVersion: v1
kind: ServiceAccount
metadata:
  name: abominable-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: abominable-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: abominable-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: abominable-role
subjects:
- kind: ServiceAccount
  name: abominable-sa
